# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrHvT1h7SUcULWGVWwGn2RRDW2pu7lb5
"""

'''
mayar sultan alhasani
group 5
id ; 446002675 '''

studentnum = int(input('enter the number of student'))
stdic=dict()

for r in range(studentnum):
  m= input(f"enter the name of student {1+r}")
  a= int(input(f"enter the grade of {m} "))
  stdic[m] = a
print(stdic)

n= input('enter the name')
y= stdic.get(n)
print(f'student grade of {n} is' ,y)

for grade in stdic.values():
    print(grade)
total = sum(stdic.values())
print('the ave:' , total/studentnum)